PREFIX skos:  <http://www.w3.org/2004/02/skos/core#> 

# Is there a region in UK that has no linked CZ regions with similar live birth count?
ASK {
?region skos:inScheme  <http://example.org/opendata/uk/regions/regionScheme> ;
   ^<http://example.org/opendata/uk/births/dimension/refArea> ?ukObs .
?ukObs !(^<http://example.org/opendata/similar-live-births>) ?czechObs .
}
