PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ex-catalog: <http://example.org/opendata/catalog/> 
PREFIX ex-catalog-publishers: <http://example.org/opendata/catalog/publishers#> 
PREFIX dcat: <http://www.w3.org/ns/dcat#> 
PREFIX dcterms: <http://purl.org/dc/terms/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 


DESCRIBE ex-catalog:catalog
